# Generated by Django 4.0.2 on 2022-02-11 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='subtotal',
            field=models.PositiveIntegerField(blank=True, default=10, null=True),
        ),
    ]
