# Generated by Django 4.0.2 on 2022-02-13 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0005_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimage',
            old_name='products',
            new_name='product',
        ),
    ]
